[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

# XChips Edition Effect (based on Bunco's Glitter)
[[patches]]
[patches.pattern]
target = 'functions/state_events.lua'
pattern = 'if effects[ii].edition then'
position = 'after'
match_indent = true
payload = '''
if scoring_hand and scoring_hand[i] and scoring_hand[i].edition and scoring_hand[i].edition.cry_mosaic then
    local xchips = G.P_CENTERS.e_cry_mosaic.config.Xchips
    hand_chips = mod_chips(hand_chips * xchips)
    update_hand_text({delay = 0}, {chips = hand_chips})
    card_eval_status_text(scoring_hand[i], 'extra', nil, percent, nil,
    {message = 'X'..xchips..' Chips',
    edition = true,
    x_chips = true})
end
'''
[[patches]]
[patches.pattern]
target = 'functions/state_events.lua'
pattern = 'if edition_effects.jokers.x_mult_mod then'
position = 'before'
match_indent = true
payload = '''
if G.jokers.cards and G.jokers.cards[i] and G.jokers.cards[i].edition and G.jokers.cards[i].edition.cry_mosaic then
    local xchips = G.P_CENTERS.e_cry_mosaic.config.Xchips
    hand_chips = mod_chips(hand_chips * xchips)
    update_hand_text({delay = 0}, {chips = hand_chips})
    card_eval_status_text(G.jokers.cards[i], 'extra', nil, percent, nil,
    {message = 'X'..xchips..' Chips',
    edition = true,
    x_chips = true})
end
'''

# Shine on Oversaturated to make it more noticable
[[patches]]
[patches.pattern]
target = 'card.lua'
pattern = "if (self.edition and self.edition.negative) or (self.ability.name == 'Antimatter' and (self.config.center.discovered or self.bypass_discovery_center)) then"
position = 'at'
match_indent = true
payload = "if (self.edition and (self.edition.negative or self.edition.cry_oversat)) or (self.ability.name == 'Antimatter' and (self.config.center.discovered or self.bypass_discovery_center)) then"

# ^Mult Edition Effect
[[patches]]
[patches.pattern]
target = 'functions/state_events.lua'
pattern = 'if effects[ii].edition then'
position = 'after'
match_indent = true
payload = '''
if scoring_hand and scoring_hand[i] and scoring_hand[i].edition and scoring_hand[i].edition.cry_astral then
    local pow_mult = G.P_CENTERS.e_cry_astral.config.pow_mult
    mult = mod_mult(mult ^ pow_mult)
    update_hand_text({delay = 0}, {mult = mult})
    card_eval_status_text(scoring_hand[i], 'extra', nil, percent, nil,
    {message = '^'..pow_mult..' Mult',
    edition = true,
    pow_mult = true})
end
'''
[[patches]]
[patches.pattern]
target = 'functions/state_events.lua'
pattern = 'if edition_effects.jokers.x_mult_mod then'
position = 'before'
match_indent = true
payload = '''
if G.jokers.cards and G.jokers.cards[i] and G.jokers.cards[i].edition and G.jokers.cards[i].edition.cry_astral then
    local pow_mult = G.P_CENTERS.e_cry_astral.config.pow_mult
    mult = mod_mult(mult ^ pow_mult)
    update_hand_text({delay = 0}, {mult = mult})
    card_eval_status_text(G.jokers.cards[i], 'extra', nil, percent, nil,
    {message = '^'..pow_mult..' Mult',
    edition = true,
    pow_mult = true})
end
'''

# Empowered Tag
[[patches]]
[patches.pattern]
target = 'card.lua'
pattern = '''card = create_card("Spectral", G.pack_cards, nil, nil, true, true, nil, 'spe')'''
position = 'at'
match_indent = true
payload = '''
card = nil --this line allows Steamodded's Pack API patch to work
if self.from_empowered then
    if i == 1 then
        card = create_card("Spectral", G.pack_cards, nil, nil, true, true, 'c_soul', 'spe')
    else
        card = create_card("Spectral", G.pack_cards, nil, nil, true, true, G.P_CENTERS.c_cry_gateway and 'c_cry_gateway' or 'c_soul', 'spe')
    end
else
    card = create_card("Spectral", G.pack_cards, nil, nil, true, true, nil, 'spe')
end
'''