[manifest]
version = "1.0.0"
dump_lua = true
priority = 1

# Add our music to music_codes, but don't use Steamodded's music API
[[patches]]
[patches.pattern] 
target = 'functions/misc_functions.lua'
pattern = '''local music_codes = { 'music1', 'music2', 'music3', 'music4', 'music5' }'''
match_indent = true
position = 'at'
payload = '''local music_codes = { 'music1', 'music2', 'music3', 'music4', 'music5', 'musicProg', 'musicExotic', 'musicBig' }'''