[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

# Copies compat with Anaglyph Deck
[[patches]]
[patches.pattern]
target = "deck.lua"
pattern = "add_tag(Tag('tag_double'))"
position = "at"
payload = "add_tag(Tag(G.GAME.used_vouchers.v_cry_clone_machine and 'tag_cry_quintuple' or G.GAME.used_vouchers.v_cry_tag_printer and 'tag_cry_quadruple' or G.GAME.used_vouchers.v_cry_copies and 'tag_cry_triple' or 'tag_double'))"
match_indent = true

# Copies compat with Diet Cola
[[patches]]
[patches.pattern]
target = "card.lua"
pattern = "add_tag(Tag('tag_double'))"
position = "at"
payload = "add_tag(Tag(G.GAME.used_vouchers.v_cry_clone_machine and 'tag_cry_quintuple' or G.GAME.used_vouchers.v_cry_tag_printer and 'tag_cry_quadruple' or G.GAME.used_vouchers.v_cry_copies and 'tag_cry_triple' or 'tag_double'))"
match_indent = true